spring.application.name=codeeditor

spring.datasource.url=jdbc:postgresql://localhost:5432/code_editor
spring.datasource.username=postgres
spring.datasource.password=31Ri1997@#$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8086

admin.seed.email=${ADMIN_EMAIL:}
admin.seed.password=${ADMIN_PASSWORD:}
admin.seed.name=CodeHive Admin

google.client.id=${GOOGLE_CLIENT_ID:}

socketio.host=0.0.0.0
socketio.port=9092

execution.timeout.seconds=10
execution.docker.enabled=true

groq.api.key=${GROQ_API_KEY:}